#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'
 
daemon_options = {
  :multiple   => false,
  :dir_mode   => :normal,
  :dir        => "/tmp/pids",
  :backtrace  => true
}
 
Daemons.run_proc('job_runner', daemon_options) do
  if ARGV.include?('--')
    ARGV.slice! 0..ARGV.index('--')
  else
    ARGV.clear
  end
  
  Dir.chdir dir
  RAILS_ENV = ARGV.first || ENV['RAILS_ENV'] || 'development'
  require File.join(File.expand_path("../trippy",__FILE__))
  
  Delayed::Worker.new.start
end